In [2]:
# Pandas Data Science Library

import numpy as np
import pandas as pd
print(pd.__version__)

2.2.2

In [3]:
# numpy --> array()
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]

In [4]:
# Pandas Series
# Series is 1D Labelled Array

s = pd.Series([10,20,30,40,50])
print(type(s))
print(s)
print(s.shape)

# In Numpy --> Only Numbers
# In Series --> Numbers + Labels (index)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
dtype: int64
(5,)

In [5]:
info = pd.Series(['John',28,6700,'Klang'],index=['name','age','sal','city'])
print(info)
print(info['name'])         # indexing
print(info.get('city'))     # getting data values using get()
print(info.iloc[0])  # --> use .iloc instead of print(info[0])

# Series is like a Dictionary + array combo

name     John
age        28
sal      6700
city    Klang
dtype: object
John
Klang
John

In [1]:
info = {'name':'John','age':28}
print(type(info))
print(info['name'])
# print(info[0])  --> dictionary didn't have index no.

<class 'dict'>
John

In [6]:
# values property
# print only values

print(info)   # --> series kind
print(info.values)  # --> numpy kind

name     John
age        28
sal      6700
city    Klang
dtype: object
['John' 28 6700 'Klang']

In [7]:
# Indexing Slicing and Using A For Loop

s = pd.Series([100,200,300,400,500,600],index=['v1','v2','v3','v4','v5','v6'])
print(s)

# 100   200   300   400   500   600
#  0     1     2     3     4     5
# -6    -5    -4    -3     -2   -1
# v1    v2    v3    v4    v5    v6

# Indexing in Series can be done by using [] or iloc[] or loc[]
print('\nIndexing in Series')
print(s.iloc[0])    # iloc used for index numbers
print(s.loc['v5'])  # loc used for labels
print(s['v2'])      # [] used for labels
print(s.iloc[-1])


print('\nSlicing in Series')
print(s[1:4])         # 4 will be excluded --> stopIndex
print(s['v1':'v5'])   # if performing slicing using labels, the end label is included

# 100 400 600
print(s[['v1','v4','v6']])  # for specific information [['','','']]
print(s[['v1','v4','v6']].values)

# conditional selection
print('\nConditional Selection')
print(s[s%3==0])    # divisible by 3

v1    100
v2    200
v3    300
v4    400
v5    500
v6    600
dtype: int64

Indexing in Series
100
500
200
600

Slicing in Series
v2    200
v3    300
v4    400
dtype: int64
v1    100
v2    200
v3    300
v4    400
v5    500
dtype: int64
v1    100
v4    400
v6    600
dtype: int64
[100 400 600]

Conditional Selection
v3    300
v6    600
dtype: int64

In [8]:
#   Using for loop
for i in s:
  print(i)

100
200
300
400
500
600

In [9]:
for k,v in s.items():
  print(k,v)

v1 100
v2 200
v3 300
v4 400
v5 500
v6 600

In [10]:
for i in enumerate(s):
  print(i)

(0, 100)
(1, 200)
(2, 300)
(3, 400)
(4, 500)
(5, 600)

In [11]:
# Pandas DataFrame
# Used to display the information in a tabular fashion (in row & column)
# Pandas DataFrame is 2D Array

data = {
    'name':['John','Alex','Smith'],
    'dept':['IT','HR','MR'],
    'sal':[6700,5600,6000],
    'city':['KL','JB','ML']
}
print(data)

{'name': ['John', 'Alex', 'Smith'], 'dept': ['IT', 'HR', 'MR'], 'sal': [6700, 5600, 6000], 'city': ['KL', 'JB', 'ML']}

In [12]:
df = pd.DataFrame(data)
df

    name dept   sal city
0   John   IT  6700   KL
1   Alex   HR  5600   JB
2  Smith   MR  6000   ML

In [13]:
# 2D Array
print(df.shape)

(3, 4)

In [14]:
data = {
    'Calories':[420,380,560],
    'Duration':[56,30,75]
}
df = pd.DataFrame(data,index=['Day1','Day2','Day3'])
df

      Calories  Duration
Day1       420        56
Day2       380        30
Day3       560        75

In [15]:
# Indexing in DataFrame
df['Calories']

Day1    420
Day2    380
Day3    560
Name: Calories, dtype: int64

In [16]:
print(df['Calories'].values)

[420 380 560]

In [17]:
# row-wise information
df.loc['Day1']

Calories    420
Duration     56
Name: Day1, dtype: int64

In [18]:
# Getting specific info - use [['','']]
df.loc[['Day1','Day3']]

      Calories  Duration
Day1       420        56
Day3       560        75